# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'default'
steps:
- script: |
    pip install flake8 pydocstyle pycodestyle mccabe
  displayName: 'Install python linters'

- script: |
    cd frontend
    yarn install
    npm run build
    cd ..
  displayName: 'npm install and build'

- script: |
    flake8 --ignore=E731,W504 --max-complexity 15 .
  displayName: 'flake8 linting'

#- script: |
#    ./node_modules/.bin/eslint .
#  displayName: 'ESLint linting'
