Document: dgpumon
Title: Debian dgpumon Manual
Author: <insert document author here>
Abstract: This manual describes what dgpumon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dgpumon/dgpumon.sgml.gz

Format: postscript
Files: /usr/share/doc/dgpumon/dgpumon.ps.gz

Format: text
Files: /usr/share/doc/dgpumon/dgpumon.text.gz

Format: HTML
Index: /usr/share/doc/dgpumon/html/index.html
Files: /usr/share/doc/dgpumon/html/*.html
