#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/dgpumon" ] && [ "$1" = remove ]; then
	invoke-rc.d dgpumon stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.6ubuntu2
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'dgpumon.service' >/dev/null || true
fi
# End automatically added section
